name: converter_uz
description: Letters converter.
version: 1.0.0
homepage: https://github.com/MirrikhSoftware/converter-uz
Author: "Bakhromjon Polat"

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
